// <auto-generated />
using System;
using CQRSProject.DataAccess.Write.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CQRSProject.DataAccess.Write.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CQRSProject.Core.Entities.UserLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("Date")
                        .HasColumnName("Date")
                        .HasMaxLength(255);

                    b.Property<double>("Height")
                        .HasColumnName("Height")
                        .HasMaxLength(255);

                    b.Property<double>("Latitude")
                        .HasColumnName("Latitude")
                        .HasMaxLength(255);

                    b.Property<double>("Longitude")
                        .HasColumnName("Longitude")
                        .HasMaxLength(255);

                    b.Property<Guid>("UserId")
                        .HasColumnName("UserId")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("UserLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
